### ISSUE TITLE
ASV Benchmark fails on kedro main branch

### ISSUE THREAD

**Issue by ravi-kumar-pilla** [kedro-org/kedro#4893]
## Description

After merging develop to main, the CI build fails -
https://github.com/kedro-org/kedro/actions/runs/15854609576/job/44714932770#step:5:2687

```bash
AttributeError: 'DataCatalog' object has no attribute 'validate_catalog'
```
## Context

* ASV benchmark fails while executing ParallelRunner benchmark tests both on RunnerMemorySuite and RunnerTimeSuite

## Expected Result

Test should pass

## Actual Result

Test failed

**Comment by ravi-kumar-pilla** [comment]
cc: @ElenaKhaustova are you aware of this or any info please add.

**Comment by ElenaKhaustova** [comment]
@ravi-kumar-pilla, I think we can close current in favour of this one: https://github.com/kedro-org/kedro/issues/4886

**Comment by ravi-kumar-pilla** [comment]
Closing in favor of #4886
